
omniauth:
  facebook_key: "1428822157336759"
  facebook_secret: "b8e47bb7a59e81360eff3ed897e0199c"
  linkedin_key: "31azcdigi8tt"
  linkedin_secret: "OKd1hmuJoNOg9J2g"
  google_oauth2_key: "928801233183"
  google_oauth2_secret: "-nMQ0dEfcaBITxzwYHZPQ3v-"

email:
  user_name: "helpalife.in"
  password: "Samuels__253325"
  domain: "helpalife.in"
  address: "smtp.gmail.com"
  port: 587


domain_name: "helpalife.in"
twitter_url: ""
youtube_url: ""
facebook_url: "https://www.facebook.com/helpalife.in"
google_plus_url: https://plus.google.com/+HelpalifeIn-blood-donors
linked_in_url: ""
sms_gateway: "https://notifysimply.herokuapp.com/api/notifications"
sms_gateway_api: "7eba8a0135593a86561a58d03bea6624"